name: Release

on:
  push:
    branches:
      - '!*'
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Install tools
      run: |
        go get -u github.com/tombell/brewer/cmd/brewer
        go get -u github.com/tombell/releasekit/cmd/releasekit
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/

    - name: Build binaries
      run: VERSION="$(basename ${GITHUB_REF})" make dist

    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /home/runner/work/
      run: |
        $GOPATH/bin/releasekit -t ${GITHUB_TOKEN} \
                               -o tombell \
                               -r zengarden \
                               -p $(git tag | sort -V | tail -2 | head -1) \
                               -n "$(basename ${GITHUB_REF})" \
                               --attachment dist/zg-linux-amd64 \
                               --attachment dist/zg-darwin-amd64 \
                               --attachment dist/zg-windows-amd64

    - name: Update Homebrew formula
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: /home/runner/work/
      run: |
        go get -u github.com/tombell/brewer/cmd/brewer
        $GOPATH/bin/brewer --token ${GITHUB_TOKEN} \
                           --owner tombell \
                           --name homebrew-formulae \
                           --formula Formula/zengarden.rb \
                           --tag "$(basename ${GITHUB_REF})" \
                           --revision ${CIRCLE_SHA1} \
                           --commit-message "Update Formula/zengarden.rb to $(basename ${GITHUB_REF})" \
                           --commit-author "Tom Bell" \
                           --commit-email "tomb@tomb.io"
